version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_DSN: redis:6379
      MONGO_URI: "mongodb+srv://user:user@mycluster.ddpqc.gcp.mongodb.net"
    networks:
      - backend

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
